diffusion_model:
  training:
    batch_size: 6
    shuffle_data: True
    num_workers: 0
    pin_memory: True
    learning_rate: 0.0001
    weight_decay: 0
    num_epochs: 1000
    save_interval: 100

  sampling:
    num_sampling_steps:  50
    guidance_scale: 7.5
    latent_dim: 64
    condition_dim: 5
    scheduler:
      scheduler_type: "ddim"

  model:
    scheduler:
      scheduler_type: "ddpm"
      num_train_timesteps: 1000
      beta_schedule: "linear"
      beta_start: 0.0001
      beta_end: 0.02
      prediction_type: "epsilon"
      clip_sample: True
    network_params:
      time_embedding_dim: 128
      condition_embedding_dim: 128
      model_channels: 256
      num_res_blocks: 3